# Generated by Django 3.2.9 on 2021-11-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('signed_in', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='products_images/')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('promotion', models.BooleanField(default=False)),
                ('discontinued', models.BooleanField(default=False)),
                ('registered_in', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
